FOOD_INGREDIENTS = {
    'pizza': ['flour', 'yeast', 'water', 'salt', 'olive oil', 'tomato sauce', 'mozzarella cheese', 'basil'],
    'burger': ['beef patty', 'burger bun', 'lettuce', 'tomato', 'onion', 'cheese', 'pickles', 'ketchup', 'mustard'],
    'pasta': ['pasta', 'tomato sauce', 'garlic', 'olive oil', 'basil', 'parmesan cheese', 'salt', 'pepper'],
    'sushi': ['rice', 'nori seaweed', 'fish', 'wasabi', 'soy sauce', 'rice vinegar', 'sugar', 'salt'],
    'ramen': ['noodles', 'broth', 'soy sauce', 'miso paste', 'pork', 'egg', 'green onions', 'seaweed'],
    'tacos': ['tortilla', 'ground beef', 'lettuce', 'cheese', 'tomato', 'sour cream', 'salsa', 'onion'],
    'burrito': ['tortilla', 'rice', 'beans', 'cheese', 'sour cream', 'guacamole', 'salsa', 'meat'],
    'sandwich': ['bread', 'cheese', 'lettuce', 'tomato', 'mayonnaise', 'mustard', 'meat'],
    'salad': ['lettuce', 'tomato', 'cucumber', 'onion', 'olive oil', 'vinegar', 'salt', 'pepper'],
    'fried rice': ['rice', 'eggs', 'soy sauce', 'vegetables', 'garlic', 'ginger', 'oil', 'salt'],
    'curry': ['curry powder', 'coconut milk', 'onion', 'garlic', 'ginger', 'tomato', 'meat', 'vegetables'],
    'soup': ['broth', 'vegetables', 'meat', 'noodles', 'salt', 'pepper', 'herbs'],
    'steak': ['beef', 'salt', 'pepper', 'butter', 'garlic', 'thyme'],
    'chicken': ['chicken', 'salt', 'pepper', 'garlic', 'olive oil', 'herbs'],
    'fish': ['fish', 'lemon', 'salt', 'pepper', 'butter', 'herbs'],
    'bread': ['flour', 'water', 'yeast', 'salt', 'sugar'],
    'cake': ['flour', 'sugar', 'eggs', 'butter', 'baking powder', 'milk', 'vanilla extract'],
    'ice cream': ['cream', 'milk', 'sugar', 'vanilla extract', 'eggs'],
    'pancakes': ['flour', 'eggs', 'milk', 'sugar', 'baking powder', 'butter', 'salt'],
    'waffles': ['flour', 'eggs', 'milk', 'sugar', 'baking powder', 'butter', 'vanilla extract'],
    'omelette': ['eggs', 'milk', 'cheese', 'butter', 'salt', 'pepper'],
    'scrambled eggs': ['eggs', 'butter', 'milk', 'salt', 'pepper'],
    'french toast': ['bread', 'eggs', 'milk', 'cinnamon', 'vanilla extract', 'butter', 'sugar'],
    'hot dog': ['sausage', 'hot dog bun', 'mustard', 'ketchup', 'onions', 'relish'],
    'nachos': ['tortilla chips', 'cheese', 'jalapenos', 'sour cream', 'guacamole', 'salsa', 'beans'],
    'quesadilla': ['tortilla', 'cheese', 'chicken', 'peppers', 'onions', 'sour cream'],
    'enchiladas': ['tortilla', 'cheese', 'meat', 'enchilada sauce', 'onions', 'sour cream'],
    'lasagna': ['pasta sheets', 'ground beef', 'tomato sauce', 'ricotta cheese', 'mozzarella', 'parmesan', 'garlic'],
    'spaghetti': ['spaghetti pasta', 'tomato sauce', 'garlic', 'olive oil', 'basil', 'parmesan cheese'],
    'fettuccine': ['fettuccine pasta', 'cream', 'butter', 'parmesan cheese', 'garlic', 'salt', 'pepper'],
    'mac and cheese': ['macaroni', 'cheese', 'milk', 'butter', 'flour', 'salt', 'pepper'],
    'risotto': ['arborio rice', 'broth', 'white wine', 'parmesan cheese', 'butter', 'onion', 'garlic'],
    'paella': ['rice', 'saffron', 'chicken', 'seafood', 'peppers', 'tomato', 'garlic', 'olive oil'],
    'biryani': ['basmati rice', 'meat', 'yogurt', 'onions', 'spices', 'saffron', 'ghee', 'herbs'],
    'fried chicken': ['chicken', 'flour', 'eggs', 'buttermilk', 'spices', 'salt', 'oil'],
    'roast chicken': ['chicken', 'butter', 'garlic', 'herbs', 'lemon', 'salt', 'pepper'],
    'chicken wings': ['chicken wings', 'hot sauce', 'butter', 'garlic powder', 'salt', 'pepper'],
    'fish and chips': ['fish', 'potatoes', 'flour', 'beer batter', 'salt', 'oil', 'vinegar'],
    'salmon': ['salmon', 'lemon', 'dill', 'butter', 'salt', 'pepper'],
    'shrimp': ['shrimp', 'garlic', 'butter', 'lemon', 'parsley', 'salt', 'pepper'],
    'lobster': ['lobster', 'butter', 'lemon', 'garlic', 'parsley', 'salt'],
    'crab': ['crab', 'butter', 'lemon', 'old bay seasoning', 'garlic'],
    'oysters': ['oysters', 'lemon', 'hot sauce', 'crackers'],
    'clam chowder': ['clams', 'potatoes', 'cream', 'bacon', 'onions', 'celery', 'flour', 'butter'],
    'tom yum': ['shrimp', 'lemongrass', 'galangal', 'lime', 'fish sauce', 'chili', 'mushrooms'],
    'pho': ['rice noodles', 'beef broth', 'beef', 'onions', 'ginger', 'star anise', 'fish sauce', 'herbs'],
    'pad thai': ['rice noodles', 'shrimp', 'eggs', 'peanuts', 'bean sprouts', 'tamarind', 'fish sauce', 'sugar'],
    'tempura': ['shrimp', 'vegetables', 'flour', 'ice water', 'eggs', 'oil'],
    'teriyaki chicken': ['chicken', 'soy sauce', 'mirin', 'sugar', 'ginger', 'garlic'],
    'dumplings': ['flour', 'water', 'meat', 'cabbage', 'ginger', 'soy sauce', 'sesame oil'],
    'spring rolls': ['rice paper', 'vegetables', 'shrimp', 'rice noodles', 'herbs', 'peanut sauce'],
    'samosa': ['flour', 'potatoes', 'peas', 'spices', 'onions', 'oil'],
    'falafel': ['chickpeas', 'onions', 'garlic', 'cumin', 'coriander', 'parsley', 'flour', 'oil'],
    'hummus': ['chickpeas', 'tahini', 'lemon juice', 'garlic', 'olive oil', 'salt'],
    'guacamole': ['avocado', 'lime juice', 'onions', 'tomato', 'cilantro', 'salt', 'jalapeno'],
    'salsa': ['tomatoes', 'onions', 'cilantro', 'lime juice', 'jalapeno', 'salt'],
    'pesto': ['basil', 'pine nuts', 'parmesan cheese', 'garlic', 'olive oil', 'salt'],
    'tzatziki': ['yogurt', 'cucumber', 'garlic', 'lemon juice', 'dill', 'olive oil', 'salt'],
    'coleslaw': ['cabbage', 'carrots', 'mayonnaise', 'vinegar', 'sugar', 'salt', 'pepper'],
    'potato salad': ['potatoes', 'mayonnaise', 'mustard', 'celery', 'onions', 'eggs', 'salt', 'pepper'],
    'caesar salad': ['romaine lettuce', 'croutons', 'parmesan cheese', 'caesar dressing', 'lemon', 'garlic'],
    'greek salad': ['tomatoes', 'cucumber', 'onions', 'feta cheese', 'olives', 'olive oil', 'oregano'],
    'caprese salad': ['tomatoes', 'mozzarella', 'basil', 'olive oil', 'balsamic vinegar', 'salt'],
    'tuna salad': ['tuna', 'mayonnaise', 'celery', 'onions', 'lemon juice', 'salt', 'pepper'],
    'chicken salad': ['chicken', 'mayonnaise', 'celery', 'grapes', 'almonds', 'salt', 'pepper'],
    'egg salad': ['eggs', 'mayonnaise', 'mustard', 'celery', 'onions', 'salt', 'pepper'],
    'club sandwich': ['bread', 'turkey', 'bacon', 'lettuce', 'tomato', 'cheese', 'mayonnaise'],
    'blt sandwich': ['bread', 'bacon', 'lettuce', 'tomato', 'mayonnaise'],
    'grilled cheese': ['bread', 'cheese', 'butter'],
    'tuna sandwich': ['bread', 'tuna', 'mayonnaise', 'lettuce', 'tomato'],
    'chicken sandwich': ['bread', 'chicken', 'lettuce', 'tomato', 'mayonnaise', 'cheese'],
    'philly cheesesteak': ['steak', 'hoagie roll', 'cheese', 'onions', 'peppers'],
    'meatball sub': ['sub roll', 'meatballs', 'marinara sauce', 'mozzarella cheese', 'parmesan'],
    'pulled pork': ['pork', 'bbq sauce', 'onions', 'coleslaw', 'burger bun'],
    'brisket': ['beef brisket', 'salt', 'pepper', 'garlic powder', 'onion powder', 'paprika'],
    'ribs': ['pork ribs', 'bbq sauce', 'brown sugar', 'paprika', 'garlic powder', 'salt', 'pepper'],
    'meatloaf': ['ground beef', 'breadcrumbs', 'eggs', 'ketchup', 'onions', 'garlic', 'salt', 'pepper'],
    'meatballs': ['ground beef', 'breadcrumbs', 'eggs', 'parmesan cheese', 'garlic', 'parsley', 'salt', 'pepper'],
    'chili': ['ground beef', 'beans', 'tomatoes', 'chili powder', 'cumin', 'onions', 'garlic'],
    'beef stew': ['beef', 'potatoes', 'carrots', 'onions', 'beef broth', 'tomato paste', 'herbs'],
    'pot roast': ['beef roast', 'potatoes', 'carrots', 'onions', 'beef broth', 'herbs', 'salt', 'pepper'],
    'shepherd\'s pie': ['ground lamb', 'mashed potatoes', 'vegetables', 'gravy', 'cheese'],
    'cottage pie': ['ground beef', 'mashed potatoes', 'vegetables', 'gravy', 'cheese'],
    'quiche': ['eggs', 'cream', 'cheese', 'pie crust', 'bacon', 'vegetables', 'salt', 'pepper'],
    'frittata': ['eggs', 'vegetables', 'cheese', 'milk', 'salt', 'pepper', 'herbs'],
    'deviled eggs': ['eggs', 'mayonnaise', 'mustard', 'paprika', 'salt', 'pepper'],
    'egg rolls': ['wrappers', 'cabbage', 'carrots', 'pork', 'soy sauce', 'ginger', 'garlic', 'oil'],
    'dim sum': ['flour', 'meat', 'shrimp', 'vegetables', 'soy sauce', 'ginger', 'garlic'],
    'baozi': ['flour', 'yeast', 'meat', 'vegetables', 'soy sauce', 'ginger', 'garlic'],
    'gyoza': ['dumpling wrappers', 'pork', 'cabbage', 'garlic', 'ginger', 'soy sauce', 'sesame oil'],
    'peking duck': ['duck', 'hoisin sauce', 'pancakes', 'cucumber', 'scallions'],
    'kung pao chicken': ['chicken', 'peanuts', 'peppers', 'soy sauce', 'vinegar', 'sugar', 'garlic', 'ginger'],
    'sweet and sour chicken': ['chicken', 'pineapple', 'peppers', 'sugar', 'vinegar', 'ketchup', 'soy sauce'],
    'general tso chicken': ['chicken', 'soy sauce', 'sugar', 'vinegar', 'garlic', 'ginger', 'chili peppers'],
    'orange chicken': ['chicken', 'orange juice', 'soy sauce', 'sugar', 'vinegar', 'garlic', 'ginger'],
    'beef and broccoli': ['beef', 'broccoli', 'soy sauce', 'oyster sauce', 'garlic', 'ginger', 'cornstarch'],
    'lo mein': ['noodles', 'vegetables', 'soy sauce', 'oyster sauce', 'sesame oil', 'garlic', 'ginger'],
    'chow mein': ['noodles', 'vegetables', 'meat', 'soy sauce', 'oyster sauce', 'garlic', 'ginger'],
    'egg foo young': ['eggs', 'bean sprouts', 'mushrooms', 'meat', 'soy sauce', 'gravy'],
    'wonton soup': ['wontons', 'broth', 'bok choy', 'green onions', 'soy sauce', 'sesame oil'],
    'hot and sour soup': ['tofu', 'mushrooms', 'bamboo shoots', 'vinegar', 'soy sauce', 'white pepper', 'eggs'],
    'minestrone': ['vegetables', 'beans', 'pasta', 'tomato', 'broth', 'herbs', 'parmesan cheese'],
    'french onion soup': ['onions', 'beef broth', 'white wine', 'bread', 'gruyere cheese', 'butter'],
    'tomato soup': ['tomatoes', 'onions', 'garlic', 'broth', 'cream', 'basil', 'salt', 'pepper'],
    'chicken noodle soup': ['chicken', 'noodles', 'carrots', 'celery', 'onions', 'broth', 'herbs'],
    'broccoli cheddar soup': ['broccoli', 'cheddar cheese', 'cream', 'broth', 'onions', 'garlic', 'flour', 'butter'],
    'butternut squash soup': ['butternut squash', 'cream', 'broth', 'onions', 'garlic', 'nutmeg', 'salt', 'pepper'],
    'gazpacho': ['tomatoes', 'cucumber', 'peppers', 'onions', 'garlic', 'olive oil', 'vinegar', 'bread'],
    'miso soup': ['miso paste', 'tofu', 'seaweed', 'dashi', 'green onions'],
    'ramen broth': ['pork bones', 'chicken', 'soy sauce', 'mirin', 'sake', 'ginger', 'garlic', 'green onions'],
    'poutine': ['french fries', 'cheese curds', 'gravy'],
    'french fries': ['potatoes', 'oil', 'salt'],
    'onion rings': ['onions', 'flour', 'eggs', 'breadcrumbs', 'oil', 'salt'],
    'mozzarella sticks': ['mozzarella cheese', 'flour', 'eggs', 'breadcrumbs', 'oil', 'marinara sauce'],
    'jalapeno poppers': ['jalapenos', 'cream cheese', 'cheddar cheese', 'bacon', 'breadcrumbs'],
    'buffalo wings': ['chicken wings', 'hot sauce', 'butter', 'garlic powder', 'cayenne pepper'],
    'chicken tenders': ['chicken', 'flour', 'eggs', 'breadcrumbs', 'oil', 'salt', 'pepper'],
    'chicken nuggets': ['chicken', 'flour', 'eggs', 'breadcrumbs', 'oil', 'salt', 'pepper'],
    'popcorn chicken': ['chicken', 'flour', 'eggs', 'breadcrumbs', 'oil', 'salt', 'pepper'],
    'calamari': ['squid', 'flour', 'eggs', 'breadcrumbs', 'oil', 'lemon', 'marinara sauce'],
    'crab cakes': ['crab', 'breadcrumbs', 'eggs', 'mayonnaise', 'mustard', 'old bay seasoning'],
    'fish tacos': ['fish', 'tortillas', 'cabbage', 'sour cream', 'lime', 'cilantro', 'salsa'],
    'shrimp tacos': ['shrimp', 'tortillas', 'cabbage', 'sour cream', 'lime', 'cilantro', 'avocado'],
    'carnitas': ['pork', 'orange juice', 'lime', 'garlic', 'cumin', 'oregano', 'salt'],
    'al pastor': ['pork', 'pineapple', 'chili peppers', 'garlic', 'vinegar', 'spices'],
    'barbacoa': ['beef', 'chipotle peppers', 'lime', 'garlic', 'cumin', 'oregano', 'bay leaves'],
    'carne asada': ['beef', 'lime', 'orange juice', 'garlic', 'cilantro', 'cumin', 'chili powder'],
    'fajitas': ['beef or chicken', 'peppers', 'onions', 'lime', 'cumin', 'chili powder', 'tortillas'],
    'chimichanga': ['tortilla', 'meat', 'beans', 'cheese', 'sour cream', 'guacamole', 'oil'],
    'tostada': ['tostada shell', 'beans', 'meat', 'lettuce', 'cheese', 'sour cream', 'salsa'],
    'tamales': ['masa', 'meat', 'corn husks', 'chili sauce', 'lard', 'broth'],
    'empanadas': ['flour', 'meat', 'vegetables', 'eggs', 'butter', 'spices'],
    'arepa': ['cornmeal', 'water', 'salt', 'cheese', 'butter'],
    'pupusa': ['masa', 'cheese', 'beans', 'pork', 'curtido'],
    'ceviche': ['fish', 'lime juice', 'onions', 'cilantro', 'tomato', 'chili peppers', 'salt'],
    'tiradito': ['fish', 'lime juice', 'aji amarillo', 'garlic', 'ginger', 'soy sauce'],
    'sashimi': ['raw fish', 'soy sauce', 'wasabi', 'ginger'],
    'nigiri': ['rice', 'raw fish', 'wasabi', 'soy sauce'],
    'maki': ['rice', 'nori', 'fish', 'vegetables', 'soy sauce', 'wasabi'],
    'california roll': ['rice', 'nori', 'crab', 'avocado', 'cucumber', 'sesame seeds'],
    'spicy tuna roll': ['rice', 'nori', 'tuna', 'spicy mayo', 'cucumber', 'sesame seeds'],
    'dragon roll': ['rice', 'nori', 'shrimp tempura', 'avocado', 'eel sauce', 'sesame seeds'],
    'rainbow roll': ['rice', 'nori', 'crab', 'avocado', 'tuna', 'salmon', 'yellowtail'],
    'udon': ['udon noodles', 'broth', 'soy sauce', 'mirin', 'green onions', 'tempura'],
    'soba': ['soba noodles', 'broth', 'soy sauce', 'mirin', 'green onions', 'wasabi'],
    'yakisoba': ['soba noodles', 'cabbage', 'carrots', 'pork', 'yakisoba sauce', 'ginger'],
    'okonomiyaki': ['flour', 'eggs', 'cabbage', 'pork', 'okonomiyaki sauce', 'mayonnaise', 'bonito flakes'],
    'takoyaki': ['flour', 'eggs', 'octopus', 'dashi', 'takoyaki sauce', 'mayonnaise', 'bonito flakes'],
    'katsu': ['pork or chicken', 'flour', 'eggs', 'panko breadcrumbs', 'oil', 'tonkatsu sauce'],
    'tonkatsu': ['pork', 'flour', 'eggs', 'panko breadcrumbs', 'oil', 'tonkatsu sauce', 'cabbage'],
    'chicken katsu': ['chicken', 'flour', 'eggs', 'panko breadcrumbs', 'oil', 'tonkatsu sauce'],
    'donburi': ['rice', 'meat', 'eggs', 'onions', 'soy sauce', 'mirin', 'dashi'],
    'oyakodon': ['rice', 'chicken', 'eggs', 'onions', 'soy sauce', 'mirin', 'dashi'],
    'gyudon': ['rice', 'beef', 'onions', 'soy sauce', 'mirin', 'sake', 'sugar'],
    'katsudon': ['rice', 'pork cutlet', 'eggs', 'onions', 'soy sauce', 'mirin', 'dashi'],
    'chirashi': ['rice', 'assorted sashimi', 'vegetables', 'soy sauce', 'wasabi'],
    'onigiri': ['rice', 'nori', 'filling', 'salt'],
    'mochi': ['rice flour', 'water', 'sugar'],
    'dorayaki': ['flour', 'eggs', 'sugar', 'honey', 'red bean paste'],
    'taiyaki': ['flour', 'eggs', 'sugar', 'red bean paste'],
    'matcha': ['matcha powder', 'hot water'],
    'boba tea': ['tea', 'milk', 'sugar', 'tapioca pearls'],
    'smoothie': ['fruit', 'yogurt', 'milk', 'honey', 'ice'],
    'milkshake': ['ice cream', 'milk', 'syrup'],
    'frappe': ['coffee', 'milk', 'ice', 'sugar', 'whipped cream'],
    'latte': ['espresso', 'steamed milk', 'milk foam'],
    'cappuccino': ['espresso', 'steamed milk', 'milk foam'],
    'espresso': ['coffee beans', 'water'],
    'americano': ['espresso', 'hot water'],
    'mocha': ['espresso', 'chocolate', 'steamed milk', 'whipped cream'],
    'macchiato': ['espresso', 'milk foam'],
    'affogato': ['ice cream', 'espresso'],
    'tiramisu': ['ladyfingers', 'mascarpone', 'eggs', 'sugar', 'coffee', 'cocoa powder'],
    'cheesecake': ['cream cheese', 'sugar', 'eggs', 'graham cracker crust', 'vanilla extract'],
    'brownie': ['chocolate', 'butter', 'sugar', 'eggs', 'flour', 'cocoa powder'],
    'cookie': ['flour', 'butter', 'sugar', 'eggs', 'chocolate chips', 'vanilla extract'],
    'cupcake': ['flour', 'sugar', 'eggs', 'butter', 'baking powder', 'milk', 'frosting'],
    'donut': ['flour', 'sugar', 'eggs', 'butter', 'yeast', 'milk', 'glaze'],
    'croissant': ['flour', 'butter', 'yeast', 'milk', 'sugar', 'salt'],
    'cinnamon roll': ['flour', 'butter', 'sugar', 'cinnamon', 'yeast', 'milk', 'cream cheese frosting'],
    'danish': ['flour', 'butter', 'yeast', 'sugar', 'eggs', 'fruit or cream filling'],
    'scone': ['flour', 'butter', 'sugar', 'baking powder', 'cream', 'eggs'],
    'muffin': ['flour', 'sugar', 'eggs', 'butter', 'baking powder', 'milk', 'fruit or chocolate'],
    'pie': ['flour', 'butter', 'sugar', 'eggs', 'fruit filling', 'cinnamon'],
    'apple pie': ['apples', 'flour', 'butter', 'sugar', 'cinnamon', 'nutmeg', 'pie crust'],
    'pumpkin pie': ['pumpkin', 'eggs', 'cream', 'sugar', 'cinnamon', 'nutmeg', 'ginger', 'pie crust'],
    'pecan pie': ['pecans', 'corn syrup', 'eggs', 'sugar', 'butter', 'vanilla extract', 'pie crust'],
    'key lime pie': ['key lime juice', 'condensed milk', 'eggs', 'graham cracker crust'],
    'lemon meringue pie': ['lemon juice', 'sugar', 'eggs', 'butter', 'cornstarch', 'meringue', 'pie crust'],
    'chocolate cake': ['flour', 'sugar', 'cocoa powder', 'eggs', 'butter', 'baking powder', 'milk', 'vanilla'],
    'vanilla cake': ['flour', 'sugar', 'eggs', 'butter', 'baking powder', 'milk', 'vanilla extract'],
    'red velvet cake': ['flour', 'sugar', 'cocoa powder', 'eggs', 'butter', 'buttermilk', 'red food coloring', 'cream cheese frosting'],
    'carrot cake': ['flour', 'sugar', 'carrots', 'eggs', 'oil', 'cinnamon', 'walnuts', 'cream cheese frosting'],
    'pound cake': ['flour', 'butter', 'sugar', 'eggs', 'vanilla extract'],
    'angel food cake': ['egg whites', 'sugar', 'flour', 'cream of tartar', 'vanilla extract'],
    'sponge cake': ['eggs', 'sugar', 'flour', 'butter', 'baking powder'],
    'layer cake': ['flour', 'sugar', 'eggs', 'butter', 'baking powder', 'milk', 'frosting'],
    'bundt cake': ['flour', 'sugar', 'eggs', 'butter', 'baking powder', 'milk', 'vanilla extract'],
    'coffee cake': ['flour', 'sugar', 'eggs', 'butter', 'sour cream', 'cinnamon', 'streusel topping'],
    'mousse': ['chocolate', 'cream', 'eggs', 'sugar'],
    'pudding': ['milk', 'sugar', 'cornstarch', 'eggs', 'vanilla extract'],
    'custard': ['milk', 'eggs', 'sugar', 'vanilla extract'],
    'creme brulee': ['cream', 'eggs', 'sugar', 'vanilla extract'],
    'flan': ['eggs', 'condensed milk', 'evaporated milk', 'sugar', 'vanilla extract'],
    'panna cotta': ['cream', 'sugar', 'gelatin', 'vanilla extract'],
    'gelato': ['milk', 'cream', 'sugar', 'eggs', 'flavorings'],
    'sorbet': ['fruit puree', 'sugar', 'water'],
    'frozen yogurt': ['yogurt', 'sugar', 'fruit'],
    'sundae': ['ice cream', 'toppings', 'whipped cream', 'cherry'],
    'banana split': ['banana', 'ice cream', 'chocolate sauce', 'whipped cream', 'nuts', 'cherry'],
    'crepe': ['flour', 'eggs', 'milk', 'butter', 'sugar', 'filling'],
    'souffle': ['eggs', 'sugar', 'flour', 'milk', 'butter', 'flavorings'],
    'profiterole': ['flour', 'eggs', 'butter', 'water', 'cream filling', 'chocolate sauce'],
    'eclair': ['flour', 'eggs', 'butter', 'water', 'pastry cream', 'chocolate glaze'],
    'macaron': ['almond flour', 'powdered sugar', 'egg whites', 'sugar', 'filling'],
    'baklava': ['phyllo dough', 'nuts', 'honey', 'butter', 'cinnamon'],
    'cannoli': ['flour', 'eggs', 'wine', 'sugar', 'ricotta cheese', 'chocolate chips', 'powdered sugar'],
    'biscotti': ['flour', 'sugar', 'eggs', 'butter', 'almonds', 'baking powder'],
    'churros': ['flour', 'water', 'butter', 'sugar', 'cinnamon', 'oil'],
    'fudge': ['chocolate', 'butter', 'condensed milk', 'sugar', 'vanilla extract'],
    'toffee': ['butter', 'sugar', 'chocolate', 'almonds'],
    'caramel': ['sugar', 'butter', 'cream', 'vanilla extract'],
    'praline': ['nuts', 'sugar', 'butter', 'cream'],
    'truffle': ['chocolate', 'cream', 'butter', 'cocoa powder'],
    'marshmallow': ['sugar', 'gelatin', 'corn syrup', 'vanilla extract'],
    'meringue': ['egg whites', 'sugar', 'cream of tartar'],
    'pavlova': ['egg whites', 'sugar', 'cornstarch', 'vinegar', 'whipped cream', 'fruit'],
    'tart': ['flour', 'butter', 'sugar', 'eggs', 'filling'],
    'cobbler': ['flour', 'sugar', 'butter', 'baking powder', 'milk', 'fruit'],
    'crumble': ['flour', 'butter', 'sugar', 'oats', 'fruit'],
    'parfait': ['yogurt', 'granola', 'fruit', 'honey'],
    'trifle': ['cake', 'custard', 'fruit', 'whipped cream', 'jelly'],
    'baked potato': ['potato', 'butter', 'sour cream', 'cheese', 'chives', 'bacon'],
    'mashed potato': ['potatoes', 'butter', 'milk', 'salt', 'pepper'],
    'hash browns': ['potatoes', 'onions', 'oil', 'salt', 'pepper'],
    'potato wedges': ['potatoes', 'oil', 'paprika', 'garlic powder', 'salt'],
    'sweet potato fries': ['sweet potatoes', 'oil', 'salt', 'paprika'],
    'roasted vegetables': ['vegetables', 'olive oil', 'salt', 'pepper', 'herbs'],
    'grilled vegetables': ['vegetables', 'olive oil', 'salt', 'pepper', 'balsamic vinegar'],
    'steamed vegetables': ['vegetables', 'water', 'salt', 'butter'],
    'stir fry': ['vegetables', 'protein', 'soy sauce', 'garlic', 'ginger', 'oil'],
    'tofu': ['soybeans', 'water', 'coagulant'],
    'tempeh': ['soybeans', 'vinegar', 'tempeh starter'],
    'seitan': ['wheat gluten', 'soy sauce', 'garlic', 'ginger', 'broth'],
    'veggie burger': ['beans', 'vegetables', 'breadcrumbs', 'spices', 'bun', 'toppings'],
    'falafel wrap': ['falafel', 'pita', 'hummus', 'tahini', 'vegetables'],
    'bibimbap': ['rice', 'vegetables', 'egg', 'gochujang', 'sesame oil', 'meat'],
    'kimchi': ['cabbage', 'chili powder', 'garlic', 'ginger', 'fish sauce', 'salt'],
    'bulgogi': ['beef', 'soy sauce', 'sugar', 'sesame oil', 'garlic', 'ginger', 'pear'],
    'galbi': ['short ribs', 'soy sauce', 'sugar', 'sesame oil', 'garlic', 'ginger'],
    'japchae': ['sweet potato noodles', 'vegetables', 'beef', 'soy sauce', 'sesame oil', 'sugar'],
    'tteokbokki': ['rice cakes', 'gochujang', 'fish cakes', 'vegetables', 'soy sauce'],
    'kimbap': ['rice', 'seaweed', 'vegetables', 'egg', 'meat', 'sesame oil'],
    'jjigae': ['tofu', 'vegetables', 'gochugaru', 'doenjang', 'garlic', 'broth'],
    'bossam': ['pork belly', 'garlic', 'ginger', 'soju', 'cabbage', 'ssam sauce'],
    'samgyeopsal': ['pork belly', 'salt', 'pepper', 'lettuce', 'ssamjang'],
    'sundubu': ['soft tofu', 'seafood', 'gochugaru', 'garlic', 'egg', 'broth'],
    'mandoo': ['dumpling wrappers', 'pork', 'tofu', 'vegetables', 'garlic', 'ginger'],
    'bagel': ['flour', 'water', 'yeast', 'salt', 'sugar', 'malt'],
    'pretzel': ['flour', 'water', 'yeast', 'salt', 'baking soda'],
    'breadstick': ['flour', 'water', 'yeast', 'salt', 'olive oil', 'garlic'],
    'focaccia': ['flour', 'water', 'yeast', 'olive oil', 'salt', 'rosemary'],
    'naan': ['flour', 'yogurt', 'yeast', 'salt', 'sugar', 'butter'],
    'pita': ['flour', 'water', 'yeast', 'salt', 'olive oil'],
    'tortilla': ['flour', 'water', 'salt', 'oil'],
    'roti': ['whole wheat flour', 'water', 'salt', 'ghee'],
    'paratha': ['whole wheat flour', 'water', 'salt', 'ghee', 'oil'],
    'chapati': ['whole wheat flour', 'water', 'salt'],
    'dosa': ['rice', 'lentils', 'fenugreek seeds', 'salt', 'oil'],
    'idli': ['rice', 'lentils', 'fenugreek seeds', 'salt'],
    'vada': ['lentils', 'onions', 'chili peppers', 'curry leaves', 'ginger', 'oil'],
    'uttapam': ['rice', 'lentils', 'onions', 'tomato', 'chili peppers', 'oil'],
    'paneer tikka': ['paneer', 'yogurt', 'spices', 'lemon juice', 'bell peppers', 'onions'],
    'butter chicken': ['chicken', 'butter', 'cream', 'tomato', 'spices', 'fenugreek'],
    'chicken tikka masala': ['chicken', 'yogurt', 'cream', 'tomato', 'spices', 'onions', 'garlic'],
    'palak paneer': ['spinach', 'paneer', 'cream', 'onions', 'tomato', 'spices'],
    'dal': ['lentils', 'onions', 'tomato', 'garlic', 'ginger', 'spices', 'ghee'],
    'chana masala': ['chickpeas', 'onions', 'tomato', 'ginger', 'garlic', 'spices'],
    'aloo gobi': ['potatoes', 'cauliflower', 'onions', 'tomato', 'spices', 'oil'],
    'tandoori chicken': ['chicken', 'yogurt', 'tandoori spices', 'lemon juice', 'ginger', 'garlic'],
    'naan bread': ['flour', 'yogurt', 'yeast', 'salt', 'sugar', 'butter', 'garlic'],
    'korma': ['meat or vegetables', 'yogurt', 'cream', 'nuts', 'spices', 'onions'],
    'vindaloo': ['meat', 'vinegar', 'garlic', 'ginger', 'chili peppers', 'spices'],
    'rogan josh': ['lamb', 'yogurt', 'tomato', 'onions', 'garlic', 'ginger', 'spices'],
    'lamb curry': ['lamb', 'onions', 'tomato', 'garlic', 'ginger', 'curry powder', 'coconut milk'],
    'coconut curry': ['coconut milk', 'curry paste', 'vegetables', 'protein', 'fish sauce', 'lime'],
    'green curry': ['green curry paste', 'coconut milk', 'vegetables', 'protein', 'fish sauce', 'basil'],
    'red curry': ['red curry paste', 'coconut milk', 'vegetables', 'protein', 'fish sauce', 'basil'],
    'massaman curry': ['massaman curry paste', 'coconut milk', 'potatoes', 'peanuts', 'meat', 'fish sauce'],
    'panang curry': ['panang curry paste', 'coconut milk', 'meat', 'lime leaves', 'fish sauce', 'basil'],
    'thai basil chicken': ['chicken', 'thai basil', 'chili peppers', 'garlic', 'fish sauce', 'soy sauce'],
    'larb': ['ground meat', 'lime juice', 'fish sauce', 'rice powder', 'mint', 'cilantro', 'shallots'],
    'som tam': ['green papaya', 'tomato', 'green beans', 'peanuts', 'lime', 'fish sauce', 'chili'],
    'khao soi': ['egg noodles', 'curry', 'coconut milk', 'chicken', 'lime', 'shallots', 'pickled vegetables'],
    'laksa': ['noodles', 'coconut milk', 'curry paste', 'seafood', 'tofu puffs', 'bean sprouts'],
    'satay': ['meat', 'lemongrass', 'turmeric', 'garlic', 'peanut sauce', 'skewers'],
    'rendang': ['beef', 'coconut milk', 'lemongrass', 'galangal', 'turmeric', 'chili', 'spices'],
    'nasi goreng': ['rice', 'shrimp paste', 'soy sauce', 'vegetables', 'egg', 'chicken'],
    'mee goreng': ['noodles', 'shrimp paste', 'soy sauce', 'vegetables', 'egg', 'tofu'],
    'gado gado': ['vegetables', 'tofu', 'tempeh', 'eggs', 'peanut sauce', 'rice cakes'],
    'bahn mi': ['baguette', 'pork', 'pate', 'pickled vegetables', 'cilantro', 'mayo', 'jalapeno'],
    'pho ga': ['rice noodles', 'chicken broth', 'chicken', 'onions', 'ginger', 'star anise', 'herbs'],
    'bun': ['rice noodles', 'grilled meat', 'vegetables', 'herbs', 'fish sauce', 'peanuts'],
    'bun cha': ['pork patties', 'rice noodles', 'fish sauce', 'vegetables', 'herbs'],
    'cao lau': ['noodles', 'pork', 'greens', 'rice crackers', 'broth'],
    'mi quang': ['noodles', 'turmeric', 'pork', 'shrimp', 'peanuts', 'herbs', 'broth'],
    'banh xeo': ['rice flour', 'turmeric', 'coconut milk', 'shrimp', 'pork', 'bean sprouts'],
    'goi cuon': ['rice paper', 'shrimp', 'pork', 'rice noodles', 'vegetables', 'herbs', 'peanut sauce'],
    'ca kho to': ['fish', 'caramel sauce', 'fish sauce', 'coconut water', 'garlic', 'shallots'],
    'thit kho': ['pork', 'eggs', 'coconut water', 'caramel sauce', 'fish sauce', 'garlic'],
    'dessert': ['sugar', 'eggs', 'cream', 'flour', 'butter', 'vanilla'],
}